/**
 * Mermaid Syntax Cleaner
 * 
 * Cleans common syntax errors in Mermaid diagrams generated by AI agents
 * that bypass the visual content tools and generate invalid syntax.
 */

interface CleaningRule {
  name: string;
  pattern: RegExp;
  replacement: string | ((match: string, ...groups: string[]) => string);
  description: string;
  enabled: boolean;
}

/**
 * Minimal cleaning rules based on common agent-generated syntax errors
 */
const cleaningRules: CleaningRule[] = [
  {
    name: 'remove-all-comments',
    pattern: /%%.*$/gm,
    replacement: '',
    description: 'Remove all comments (everything after %%) from Mermaid syntax',
    enabled: true
  },
  {
    name: 'remove-parentheses-from-nodes',
    pattern: /(\w+\[[^[\]]*)\(([^)]*)\)([^[\]]*\])/g,
    replacement: '$1$2$3',
    description: 'Remove parentheses from node labels that can break syntax',
    enabled: true
  },
  {
    name: 'fix-arrow-labels',
    pattern: /(\w+)\s+(--|-\.-)(\s+)(\w+):\s*([^\n]+)/gm,
    replacement: '$1 $2>|"$4: $5"| $4',
    description: 'Fix invalid arrow syntax with labels to proper Mermaid arrow label format',
    enabled: true
  },
  {
    name: 'remove-empty-lines',
    pattern: /^\s*$/gm,
    replacement: '',
    description: 'Remove empty lines left after comment removal',
    enabled: true
  }
];

interface CleaningResult {
  cleaned: string;
  applied: string[];
  warnings: string[];
}

/**
 * Clean Mermaid syntax by applying enabled cleaning rules
 * 
 * @param chart - Raw Mermaid diagram syntax
 * @returns Object containing cleaned syntax and metadata about applied rules
 */
export const cleanMermaidSyntax = (chart: string): CleaningResult => {
  if (!chart || typeof chart !== 'string') {
    return {
      cleaned: '',
      applied: [],
      warnings: ['Invalid input: chart must be a non-empty string']
    };
  }

  let cleaned = chart;
  const applied: string[] = [];
  const warnings: string[] = [];

  // Apply each enabled cleaning rule
  for (const rule of cleaningRules.filter(r => r.enabled)) {
    try {
      const before = cleaned;
      
      if (typeof rule.replacement === 'function') {
        cleaned = cleaned.replace(rule.pattern, rule.replacement);
      } else {
        cleaned = cleaned.replace(rule.pattern, rule.replacement);
      }
      
      // Track which rules were applied
      if (before !== cleaned) {
        applied.push(rule.name);
      }
    } catch (error) {
      warnings.push(`Failed to apply rule '${rule.name}': ${error instanceof Error ? error.message : 'Unknown error'}`);
    }
  }

  // Final cleanup - trim whitespace
  cleaned = cleaned.trim();

  return {
    cleaned,
    applied,
    warnings
  };
};

/**
 * Get information about available cleaning rules
 * 
 * @returns Array of cleaning rule information
 */
export const getCleaningRules = () => {
  return cleaningRules.map(rule => ({
    name: rule.name,
    description: rule.description,
    enabled: rule.enabled
  }));
};

/**
 * Enable or disable a specific cleaning rule
 * 
 * @param ruleName - Name of the rule to toggle
 * @param enabled - Whether to enable or disable the rule
 * @returns Success status
 */
export const toggleCleaningRule = (ruleName: string, enabled: boolean): boolean => {
  const rule = cleaningRules.find(r => r.name === ruleName);
  if (rule) {
    rule.enabled = enabled;
    return true;
  }
  return false;
};

/**
 * Validate if a string contains valid Mermaid syntax patterns
 * Basic validation - checks for common Mermaid diagram types
 * 
 * @param chart - Mermaid diagram syntax to validate
 * @returns Whether the syntax appears to be valid Mermaid
 */
export const isValidMermaidSyntax = (chart: string): boolean => {
  if (!chart || typeof chart !== 'string') {
    return false;
  }

  const trimmed = chart.trim();
  
  // Check for common Mermaid diagram type declarations
  const mermaidPatterns = [
    /^graph\s+(TD|TB|BT|RL|LR)/i,
    /^flowchart\s+(TD|TB|BT|RL|LR)/i,
    /^sequenceDiagram/i,
    /^gantt/i,
    /^pie/i,
    /^journey/i,
    /^gitGraph/i,
    /^erDiagram/i,
    /^classDiagram/i,
    /^stateDiagram/i,
    /^mindmap/i,
    /^timeline/i,
    /^sankey-beta/i,
    /^requirement/i,
    /^c4Context/i
  ];

  return mermaidPatterns.some(pattern => pattern.test(trimmed));
};

/**
 * Clean and validate Mermaid syntax in one step
 * 
 * @param chart - Raw Mermaid diagram syntax
 * @returns Cleaned syntax with validation status
 */
export const cleanAndValidate = (chart: string) => {
  const result = cleanMermaidSyntax(chart);
  const isValid = isValidMermaidSyntax(result.cleaned);
  
  return {
    ...result,
    isValid,
    originalValid: isValidMermaidSyntax(chart)
  };
};
